import asyncio
import os
from google.adk.apps import App
from google.adk.runners import InMemoryRunner
from google.genai import types
from agents.v2.workflow import get_refactor_workflow

def run_workflow_sync(request_dict: dict, provider: str, api_key: str):
    """Synchronous wrapper to run the ADK workflow and extract the result."""
    
    # Set the API keys in the environment so ADK models (Gemini/LiteLLM) can pick them up automatically
    if provider.lower() == "gemini":
        os.environ["GEMINI_API_KEY"] = api_key
    elif provider.lower() == "openai":
        os.environ["OPENAI_API_KEY"] = api_key
        
    refactor_workflow = get_refactor_workflow(provider)
    workflow_app = App(name="mark-me-down-v2", root_agent=refactor_workflow)
    runner = InMemoryRunner(app=workflow_app)
    
    return asyncio.run(_run_workflow_async(runner, request_dict, provider, api_key))

async def _run_workflow_async(runner, request_dict: dict, provider: str, api_key: str):
    session = await runner.session_service.create_session(
        app_name="mark-me-down-v2", user_id="local_user"
    )
    
    # Pre-inject provider and key into the workflow context state if possible,
    # or just pass it in node_input. For our router node, it only accepts request fields,
    # but the runner state isn't easily pre-injected before the first node runs from user input.
    # We will modify the workflow.py to accept provider and api_key in the input,
    # or just use env vars in rag_service, but the user wants to support dynamic toggle.
    # Since router_node builds UserRefactorRequest, it will ignore extra fields by default if not strictly validating.
    # Actually, we can inject into session state.
    session_state = {"provider": provider, "api_key": api_key}
    await runner.session_service.save_session_state(session.id, session_state)
    
    final_output = None
    similarity_score = None
    
    # We just send the request_dict as a dict
    async for event in runner.run_async(
        user_id="local_user",
        session_id=session.id,
        new_message=request_dict
    ):
        if event.output is not None:
            # We want to capture the final output from note_refactor_agent
            if isinstance(event.output, types.Content):
                # We can extract text from Content
                final_output = event.output.parts[0].text
            elif isinstance(event.output, str):
                final_output = event.output
        
    # We need to retrieve the similarity score from the state if RAG ran
    final_session = await runner.session_service.get_session(session.id)
    state = final_session.state if final_session else {}
    template_match = state.get("template_match")
    if template_match and hasattr(template_match, 'similarity'):
        similarity_score = template_match.similarity
    elif template_match and isinstance(template_match, dict):
        similarity_score = template_match.get("similarity")
        
    # fallback
    if not final_output:
        final_output = "Error: No markdown output was generated by the workflow."

    return final_output, similarity_score, template_match
